# Generated by Django 4.1 on 2022-08-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_city_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='turf.district'),
            preserve_default=False,
        ),
    ]
