# Generated by Django 4.1 on 2022-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_vendororder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='VendorOrder',
        ),
    ]
